apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
  labels:
    app: pg 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pg 
    spec:
      containers:
      - name: pg 
        image: registry.takima.io/school/proxy/postgres:latest 
        resources:
          requests:
            memory: "192Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "1"
        ports:
        - containerPort: 5432 
        env:
        - name: POSTGRES_USER 
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: username 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: password 
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: db
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: pg-config
              key: db_path 
        volumeMounts:
          - name: pg-pvc
            mountPath: /var/lib/postgresql/data 

      imagePullSecrets:
        - name: takima-school-registry
      volumes:
        - name: pg-pvc
          persistentVolumeClaim: 
            claimName: pg-db 
