{{- if .Values.front.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}-front
spec:
  selector:
    app: {{ include "chart.name" . }}-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}