# Default values for CDB app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# We have only done front for now
name: cdb
global:
  namespace: loic-perrin

api:
  enabled: true
  name: api
  ingress:
    tlsEnabled: false
    host: api.loic-perrin.cpe.takima.school
  replicaCount: 1

  image:
    repository: registry.gitlab.com/takima-school/images/cdb/api
    tag: latest
    pullPolicy: IfNotPresent

  service:
    protocol: TCP
    port: 8080

  resources:
    requests:
      memory: "192Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "2"

  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001

  livenessProbe:
    path: /actuator/health/liveness
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

  readinessProbe:
    path: /actuator/health/readiness
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

front:
  enabled: true
  image:
    repository: registry.gitlab.com/takima-school/images/cdb/www
    tag: latest
  replicaCount: 1
  ingress:
    tlsEnabled: true
    host: www.loic-perrin.cpe.takima.school


pg:
  enabled: true
  teamId: "formation"
  port: "5432"
  db:
    name: cdb
  numberOfInstances: 2
  databases:
    cdb: cdb
  volume:
    size: 1Gi
  users:
    cdb:
      - superuser
      - createdb