apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}-api
spec:
  selector:
    app: {{ include "chart.name" . }}-api
  ports:
    - protocol: {{ .Values.api.service.protocol}}
      port: {{ .Values.api.service.port}}
      targetPort: {{ .Values.api.service.port}}